language: go

go:
  - tip
  - 1.13.x

env:
  - GO111MODULE=off

before_script:
  - rm -f go.sum
  - go get -tags "reuseport quic kcp zookeeper etcd consul ping utp redis" -v github.com/smallnest/rpcx/...
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - goveralls -service=travis-ci

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
